# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SvetlanaSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
