# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SvetlanaSite', '0004_book_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
