# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SvetlanaSite', '0005_picture_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='img',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='picture',
            name='img2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='img3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='img4',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='img5',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='img6',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
