# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SvetlanaSite', '0006_auto_20180522_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='img6',
        ),
        migrations.AlterField(
            model_name='picture',
            name='img1',
            field=models.ImageField(blank=True, upload_to='im'),
        ),
    ]
