# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-23 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SvetlanaSite', '0007_auto_20180522_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='year',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='img1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
