# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-23 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SvetlanaSite', '0009_auto_20180523_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='year',
            field=models.PositiveIntegerField(verbose_name=2017),
        ),
    ]
