# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-23 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SvetlanaSite', '0012_picture_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='year',
        ),
        migrations.AddField(
            model_name='picture',
            name='year1',
            field=models.PositiveIntegerField(default=2017),
            preserve_default=False,
        ),
    ]
